# Generated by Django 4.2.4 on 2024-01-23 19:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('client_email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('client_fio', models.CharField(max_length=500, verbose_name='фио')),
                ('client_comment', models.CharField(max_length=500, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('client_fio',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True, verbose_name='название')),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 1, 23, 22, 16, 42, 517531), verbose_name='время и дата рассылки')),
                ('frequency', models.CharField(choices=[('ежедневно', 'daily'), ('еженедельно', 'weekly'), ('ежемесячно', 'monthly')], default='daily', max_length=11, verbose_name='периодичность')),
                ('mailing_status', models.CharField(blank=True, choices=[('завершена', 'завершена'), ('создана', 'создана'), ('запущена', 'запущена')], default='создана', null=True, verbose_name='статус')),
                ('subject', models.CharField(blank=True, null=True, verbose_name='тема письма')),
                ('body', models.CharField(blank=True, null=True, verbose_name='тело письма')),
                ('client_email', models.ManyToManyField(to='mailing.client', verbose_name='клиенты')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('frequency',),
            },
        ),
        migrations.CreateModel(
            name='Log_Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_last_attempt', models.DateTimeField(verbose_name='дата и время последней попытки')),
                ('status_attempt', models.CharField(choices=[('УСПЕШНО', 'УСПЕШНО'), ('НЕ УСПЕШНО', 'НЕ УСПЕШНО')], verbose_name='статус попытки')),
                ('answer_mail_server', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='клиентs')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='название')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылки',
                'ordering': ('status_attempt',),
            },
        ),
    ]
