# Generated by Django 4.2.4 on 2024-02-25 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('client_fio', models.CharField(max_length=500, verbose_name='фио')),
                ('client_comment', models.CharField(max_length=500, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('client_fio',),
            },
        ),
        migrations.CreateModel(
            name='Log_Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_last_attempt', models.DateTimeField(verbose_name='дата и время последней попытки')),
                ('status_attempt', models.CharField(choices=[('успешно', 'успешно'), ('не успешно', 'не успешно')], verbose_name='статус попытки')),
                ('answer_mail_server', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылки',
                'ordering': ('status_attempt',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_mailing', models.DateTimeField(default=datetime.datetime(2024, 2, 25, 16, 54, 31, 264), verbose_name='время рассылки')),
                ('frequency', models.CharField(choices=[('ежедневно', 'ежедневно'), ('еженедельно', 'еженедельно'), ('ежемесячно', 'ежемесячно')], default='ежедневно', max_length=20, verbose_name='периодичность')),
                ('status_mailing', models.CharField(choices=[('создана', 'создана'), ('запущена', 'запущена'), ('завершена', 'завершена'), ('отключена', 'отключена')], default='создана', max_length=20, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('frequency',),
            },
        ),
        migrations.CreateModel(
            name='Text_Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, null=True, verbose_name='тема письма')),
                ('body', models.CharField(blank=True, null=True, verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('subject',),
            },
        ),
    ]
