# Generated by Django 4.2.4 on 2024-02-25 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_mailing',
            name='owner_text_mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор:'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='client_email',
            field=models.ManyToManyField(to='mailing.client', verbose_name='клиенты'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='massage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.text_mailing', verbose_name='сообщение:'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='owner_mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор:'),
        ),
        migrations.AddField(
            model_name='log_mailing',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылка'),
        ),
        migrations.AddField(
            model_name='client',
            name='owner_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор:'),
        ),
    ]
