# Generated by Django 4.2.4 on 2024-01-29 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 19, 58, 4, 34188), verbose_name='время и дата рассылки'),
        ),
    ]
