# Generated by Django 4.2.4 on 2024-02-18 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 20, 3, 48, 471700), verbose_name='время и дата рассылки'),
        ),
    ]
