# Generated by Django 4.2.4 on 2024-02-25 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 25, 16, 56, 1, 241678), verbose_name='время рассылки'),
        ),
    ]
