# Generated by Django 4.2.4 on 2024-01-29 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 21, 1, 24, 554227), verbose_name='время и дата рассылки'),
        ),
    ]
