# Generated by Django 4.2.4 on 2024-02-18 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_time_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.time(0, 0), verbose_name='время рассылки'),
        ),
    ]
