# Generated by Django 4.2.4 on 2024-02-18 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_time_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 20, 20, 31, 522518), verbose_name='время рассылки'),
        ),
    ]
