# Generated by Django 4.2.4 on 2024-02-18 18:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_time_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 21, 29, 51, 190940), verbose_name='время рассылки'),
        ),
        migrations.RemoveField(
            model_name='text_mailing',
            name='client_email',
        ),
        migrations.AddField(
            model_name='text_mailing',
            name='client_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='клиенты'),
        ),
    ]
