# Generated by Django 4.2.4 on 2024-01-30 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 20, 35, 26, 770379), verbose_name='время и дата рассылки'),
        ),
    ]
