# Generated by Django 4.2.4 on 2024-02-18 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailing_time_mailing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 21, 31, 38, 636011), verbose_name='время рассылки'),
        ),
        migrations.RemoveField(
            model_name='text_mailing',
            name='client_email',
        ),
        migrations.AddField(
            model_name='text_mailing',
            name='client_email',
            field=models.ManyToManyField(blank=True, null=True, to='mailing.client', verbose_name='клиенты'),
        ),
    ]
