# Generated by Django 4.2.4 on 2024-02-18 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailing_options_alter_mailing_time_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 21, 48, 30, 572820), verbose_name='время рассылки'),
        ),
        migrations.AlterField(
            model_name='text_mailing',
            name='client_email',
            field=models.ManyToManyField(to='mailing.client', verbose_name='клиенты'),
        ),
    ]
