# Generated by Django 4.2.4 on 2024-02-18 19:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailing_time_mailing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_mailing',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 22, 32, 13, 193488), verbose_name='время рассылки'),
        ),
    ]
