# Generated by Django 4.2.4 on 2024-02-19 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_text_mailing_frequency_alter_mailing_time_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 22, 57, 48, 324010), verbose_name='время рассылки'),
        ),
    ]
