# Generated by Django 4.2.4 on 2024-02-19 20:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0011_alter_mailing_time_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='owner_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор:'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='owner_mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор:'),
        ),
        migrations.AddField(
            model_name='text_mailing',
            name='owner_text_mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор:'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 23, 43, 37, 521985), verbose_name='время рассылки'),
        ),
    ]
