# Generated by Django 4.2.4 on 2024-02-20 10:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_client_owner_client_mailing_owner_mailing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_mailing',
            name='client',
        ),
        migrations.RemoveField(
            model_name='text_mailing',
            name='frequency',
        ),
        migrations.AddField(
            model_name='mailing',
            name='massage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.text_mailing', verbose_name='автор:'),
        ),
        migrations.AlterField(
            model_name='log_mailing',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 13, 37, 57, 154783), verbose_name='время рассылки'),
        ),
    ]
