# Generated by Django 4.2.4 on 2024-02-20 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_remove_log_mailing_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_mailing',
            name='client_email',
        ),
        migrations.AddField(
            model_name='mailing',
            name='client_email',
            field=models.ManyToManyField(to='mailing.client', verbose_name='клиенты'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 14, 0, 50, 661822), verbose_name='время рассылки'),
        ),
    ]
