# Generated by Django 4.2.4 on 2024-02-21 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0017_alter_mailing_massage_alter_mailing_time_mailing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='owner_client',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='owner_mailing',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='text_mailing',
            old_name='owner_text_mailing',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 13, 18, 47, 299805), verbose_name='время рассылки'),
        ),
    ]
