# Generated by Django 4.2.4 on 2024-02-21 18:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0020_alter_mailing_massage_alter_mailing_time_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='massage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.text_mailing', verbose_name='сообщение:'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='time_mailing',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 21, 3, 58, 57937), verbose_name='время рассылки'),
        ),
    ]
