# Generated by Django 4.2.4 on 2024-02-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.CharField(max_length=500, verbose_name='содержимое статьи'),
        ),
    ]
