# Generated by Django 4.2.4 on 2024-01-30 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_price',), 'permissions': (('set_product_description', 'редактирование описания продукта'), ('set_product_category', 'редактирование категории продукт'), ('set_product_price', 'редактирования цены продукт'), ('set_is_published', 'редактирования статуса публикации')), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('product_name',), 'permissions': (('set_product_name', 'редактирование продукта'), ('set_number_version', 'редактирование номера версии'), ('set_name_version', 'редактирование названии версии'), ('set_is_current_version', 'редактирование статуса версии')), 'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
        migrations.AddField(
            model_name='version',
            name='owner_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='добавил:'),
        ),
    ]
