# Generated by Django 4.2.4 on 2024-01-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_alter_version_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.version', verbose_name='автор версии'),
        ),
    ]
