# Generated by Django 4.2.4 on 2024-01-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_product_owner_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_price',), 'permissions': (('set_product_description', 'редактирование описания продукта'), ('set_product_category', 'редактирование категории продукт'), ('set_product_price', 'редактирования цены продукт'), ('set_is_published', 'статус публикации')), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
